apiVersion: v1
kind: ConfigMap
metadata:
  name: api-bancario-config
  namespace: bancario
data:
  QUARKUS_PROFILE: prod
  QUARKUS_HTTP_HOST: "0.0.0.0"
  QUARKUS_DATASOURCE_DB_KIND: mssql
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=bancario_db;encrypt=false"
  QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
